name: Daily Data Processing

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  process_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
<<<<<<< HEAD
          python-version: "3.11.3"
=======
          python-version: "3.10.2"  
>>>>>>> 13dd154 (Add.yml)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have a requirements file, specify it here

      - name: Run get_data_daily.py
        run: python get_data_daily.py

<<<<<<< HEAD
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have a requirements file, specify it here

=======
>>>>>>> 13dd154 (Add.yml)
      - name: Run train_model_daily.py

        run: python train_model_daily.py

