# This workflow will install Python dependencies, run get_data_daily.py and then train_model_daily.py
# F

name: get_data_daily

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  issues: write
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    
    - name: Run get_data_daily.py
      run: |
        python get_data_daily.py
        git config --global user.email "
        git config --global user.name "
        git add .
        git commit -m "Update data"
        git push origin master
    - name: Run train_model_daily.py
      run: |
        python train_model_daily.py
        git config --global user.email "
        git config --global user.name "
        git add .
        git commit -m "Update model"
        git push origin master
      
