# This workflow will install Python dependencies, run get_data_daily.py and then train_model_daily.py every 1 minute


name: Daily Data Update

on:
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: "3.8"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run helloaction.py
          run: | 
            #python helloaction.py

# mail :- 45873305+bismohamed@users.noreply.github.com
# name :- Mohamed Abd-El-Gani
# commit message :- hello actions and push to main branch using github actions and email and name are set to github actions
# commit hash :- 0f0b0f0
# commit date :- 2021-05-30 21:30:00
        
        - name: push to main branch
          run: |
            git config --global user.email "45873305+bismohamed@users.noreply.github.com"
            git config --global user.name "Mohamed Abd-El-Gani"
            git add .
            git commit -m "hello actions"
            git push origin master
            



