# This workflow will install Python dependencies, run get_data_daily.py and then train_model_daily.py every 1 minute


name: Daily Data Update 2025

on:
  schedule:
    - cron: '37 13 * * *'

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: "3.8"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run get_data_daily.py
          run: |
            python get_data_daily.py
        - name: Run train_model_daily.py
          run: |
            python train_model_daily.py
