name: Naive Cron Job

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run cron job
        run: |
          # Replace this with the command you want to run
          echo "Running cron job"
