# This workflow will install Python dependencies, run get_data_daily.py and then train_model_daily.py every 1 minute


name: Daily Data Update

on:
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: "3.8"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run get_data_daily.py
          run: |
            python get_data_daily.py
        #- name: Run train_model_daily.py
          #run: |
            #python train_model_daily.py
        - name: commit files
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git diff-index --quiet HEAD || (git commit -a -m "Updating data Actions" --allow-empty)
          
        - name: push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.PAT_TOKEN23 }}
            branch: main 

